### ISSUE TITLE
About accessing it 

### ISSUE THREAD

**Issue by bhargavaganti** [nathanschwarz/OpenBCI_Ganglion_parser_CSHARP#1]
Hey can you give a sample code and where should we pass as i already followed the steps but how to use process_data and i need to access the raw data

**Comment by karthage-spartacus** [comment]
Hello,

the process_data function is not implemented, it's just an example. It's basically where you'll be processing the data, but you have to implement it as I don't know what you'll do with the data. 

What do you mean by RAW data ? Each time you receive a buffer from the bluetooth, just pass it into the `Ganglion.parse()` function.
You'll have 2 samples per message from the Ganglion (the Ganglion refresh rate is twice as fast as the BLE latency, for more info check the Ganglion documentation) so you'll need to process each samples to have valid deltas.
To do so just call `ganglion.process_sample(x)` with x being either 0 or 1 (0 is the first sample, 1 is the second).
Then the `Ganglion.data` which is typed as `Int32[4]` will be filled with the parsed sample.
For example if you need to access the first value of the first sample you'll be doing something like:
`
ganglion.process_sample(0);
Int32 first_value = ganglion.data[0];
`

**Comment by bhargavaganti** [comment]
ok how about all 4 data values as i am getting errors in it as its been delayed so you mean to get 4 values ganglion. Here is this method we need to process for getting raw data 

ganglion.process_sample(0); Int32 first_value = ganglion.data[0];
ganglion.process_sample(1); Int32 second_value = ganglion.data[1];
ganglion.process_sample(2); Int32 third_value = ganglion.data[2];
ganglion.process_sample(3); Int32 first_value = ganglion.data[3];

**Comment by karthage-spartacus** [comment]
No, you're almost there.
The ganglion gives 2 samples per message, each containing 4 values : 

//process the first sample
ganglion.process_sample(0);
 Int32 first_value = ganglion.data[0];
 Int32 second_value = ganglion.data[1];
 Int32 third_value = ganglion.data[2];
 Int32 forth_value = ganglion.data[3];

//process the second sample
ganglion.process_sample(1);
 Int32 first_value = ganglion.data[0];
 Int32 second_value = ganglion.data[1];
 Int32 third_value = ganglion.data[2];
 Int32 forth_value = ganglion.data[3];

**Comment by bhargavaganti** [comment]
ok but what are the channel data i mean 4 channels raw data and accelerometer and impedance 4

**Comment by karthage-spartacus** [comment]
check the attributes section from the README:

> ganglion.id - (byte) : use this attribute to know what was the last Ganglion messsage ID.
> 
> ganglion.accelerometer - (Int32[3]) : use this attribute to get the x, y and z axis of the Ganglion accelerometer.
> 
> ganglion.data - (Int32[4]) : use this attribute to get the current values of the Ganglion EEG.
> 
> ganglion.last_ascii_msg - (String) : use this attribute to access the last ascii value sent by the Ganglion.
> 
> ganglion.impedance_channels - (int[5]) : use this attribute to access the impedance values sent by the Ganglion, respectively : 1, 2, 3, 4, ref.

**Comment by bhargavaganti** [comment]
yes i did but the question for is when i access ganglion.data has to provide all the 4 channels raw data(if i am not wrong) but its going on incremental and negative values so or else can you share your sample unity project with a csv file so i can just debug

**Comment by karthage-spartacus** [comment]
Yes, because an EEG value is basically an impedance value which can be negative or positive.
As told in the Ganglion documentation, the data is incrementing or decrementing because the first message contains the starting values, then it'll only contains the deltas.

**Comment by karthage-spartacus** [comment]
You can use the data in the examples of the Ganglion documentation here:
http://docs.openbci.com/Hardware/08-Ganglion_Data_Format#ganglion-data-format-example-interpreting-ganglion-data

**Comment by bhargavaganti** [comment]
if it is possible to share a sample project that would very benefit for me to debug
